[grid_config]
grid_dimensions = [10,10,10]
particle_position_method = "FillGrid"
#particle_position_method = "RandomParticlePositions"
#Amount particles. If particle_position_method is set to "FillGrid" value will be ignored.
num_particles = 1000
T = 0.5
external_field = 0

#true: Initialize all spins with Spin up.
#false: Initialize all spins with random orientation.
spin_up_init = false

#Couplings are randomly selected by a gaussian distribution
coupling_mean = 0.0
coupling_variance = 1.0

#Number of Datapoints to store in the grid history
history_capacity = 100

save_path = "./results"
skip_save = 10_000
 

[simulation_config]
num_grids = 0
#amount of simulation steps every grid performs before joining with other threads
steps_per_sweep = 1_000
#amount of Sweeps the simulation makes. Will not be used if simulation is started as app. 
num_sweeps = 100
histo_width = 0.1

[pt_config]
num_grids_equal_T = 4
T_start = 0.5
T_end = 2.0
linear_m = 0.035
linear_dT0 = 0.03
