[grid_config]
grid_dimensions = [8,8,8]
particle_position_method = "FillGrid"
#particle_position_method = "RandomParticlePositions"
#Amount particles. If particle_position_method is set to "FillGrid" value will be ignored.
num_particles = 64
T = 0.5
external_field = 0

#true: Initialize all spins with Spin up.
#false: Initialize all spins with random orientation.
spin_up_init = false

#Couplings are randomly selected by a gaussian distribution
coupling_mean = 0.0
coupling_variance = 1.0

#Number of Datapoints to store in the grid history
history_capacity = 100

#default path for saving results. Can be overwritten by "path=" commandline argument 
save_path = "./results"
#skips N runs of saving. If N=100 every 100th  Metropolis-Step is saved.
skip_save = 6_400
 

[simulation_config]
num_grids = 0
#amount of simulation steps every grid performs before joining with other threads
steps_per_sweep = 64
#amount of Sweeps the simulation makes. Will not be used if simulation is started as app. 
num_sweeps = 1_000_000
histo_width = 0.1

[pt_config]
num_grids_equal_T = 4
T_start = 0.5
T_end = 2.0
linear_m = 0.035
linear_dT0 = 0.03
